name: Continuous integration

on: 
  pull_request:
    paths:
      - "**.wdl"  # Workflow files and task 
      - "**.yml"  # Ci configuration, tests and docker images 
      - "!docs/**"

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Womtool validate and submodule up to date.
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: install miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          channels: conda-forge,bioconda,defaults
      - name: install requirements
        run: conda install cromwell miniwdl wdl-aid
      - name: run linting
        run: bash scripts/biowdl_lint.sh
  test:
    needs: lint  # Don't start testing before the lint has succeeded.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [
          "paired_end_zipped",
          "paired_end",
          "single_end_zipped",
          "single_end_zipped_contaminations",
          "single_end"
        ]
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: install miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          channels: conda-forge,bioconda,defaults
      - name: install requirements
        run: conda install  --file requirements-test.txt
      - name: Run test
        run: pytest --keep-workflow-wd-on-fail --tag ${{ matrix.test }} tests/
      - name: Check logs in case of failure
        if: ${{ failure() }}
        # Get the last 1000 lines of the cromwell log to catch the error.
        run: bash -c 'tail -n 1000 /tmp/pytest_workflow_*/*/log.out'
    